PUT http://localhost:8090/events/4
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQHRlc3QuY29tIiwiZXhwIjoxNzU2ODA2OTczLCJ1c2VySWQiOjJ9.Fjk8NroOQ_j-mnjJWvpiEPIHQ_PJZY6XDyo-rOB3TI0

{
  "eventName":"OuluSec Updated",
  "Description":"Security event",
  "Location": "Hiiloitie 3, Oulu",
  "capacicy": 30,
  "DateTime": "2025-01-01T15:30:00.00Z"
}
